# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b6fb3cd05a2a52bea86c7ec2520f4fcf"
name = "the bot"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "unauthenticated_read_product_listings"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
